# Generated by Django 5.1 on 2024-08-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='experience',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
