# Generated by Django 5.1 on 2024-08-19 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0001_initial'),
        ('job_app', '0002_alter_jobs_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='field_preferences',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_app.category'),
            preserve_default=False,
        ),
    ]
