# Generated by Django 5.1 on 2024-08-19 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_profile_field_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='field_preferences',
        ),
    ]
